### ISSUE TITLE
Error at Web Version

### ISSUE THREAD

**Issue by synapp009** [quentinleguennec/flutter-arrow-path#1]
Your code (example/lib/main.dart) throws an error when I try to use it with the javascript  Browser version in Chrome.

flutter dctor -v
```

[✓] Flutter (Channel dev, v1.13.5, on Mac OS X 10.14.6 18G95, locale de-DE)
    • Flutter version 1.13.5 at /Users/michaelberger/development/flutter
    • Framework revision 41a911099b (vor 6 Tagen), 2019-12-19 13:48:02 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/michaelberger/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • iPhone 11 Pro Max • 9ED807EB-5D04-46ED-B807-11B9E9424FC0 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • Chrome            • chrome                               • web-javascript • Google
      Chrome 79.0.3945.88
    • Web Server        • web-server                           • web-javascript • Flutter
      Tools
```

This is the error:
`
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded application in 1.327ms.
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following UnimplementedError was thrown during paint():
UnimplementedError
The relevant error-causing widget was:
CustomPaint org-dartlang-app:///packages/synapp/main.dart:44:16
When the exception was thrown, this was the stack:
[38;5;248mthrow_ (package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart:196:49)[39;49m
[38;5;248m[_getPosTan] (package:build_web_compilers/lib/ui/src/ui/path_metrics.dart:115:46)[39;49m
[38;5;248mgetTangentForOffset (package:build_web_compilers/lib/ui/src/ui/path_metrics.dart:105:32)[39;49m
[38;5;248m_make[39;49m
[38;5;248mmake[39;49m
[38;5;248mpaint[39;49m
[38;5;244m[_paintWithPainter][39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mdefaultPaint[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244mpushLayer[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244m_repaintCompositedChild[39;49m
[38;5;244mrepaintCompositedChild[39;49m
[38;5;244m[_compositeChild][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244m_repaintCompositedChild[39;49m
[38;5;244mrepaintCompositedChild[39;49m
[38;5;244m[_compositeChild][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mdefaultPaint[39;49m
[38;5;244mpaintStack[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244mpaintChild[39;49m
[38;5;244mpaint[39;49m
[38;5;244m[_paintWithContext][39;49m
[38;5;244m_repaintCompositedChild[39;49m
[38;5;244mrepaintCompositedChild[39;49m
[38;5;244mflushPaint[39;49m
[38;5;244mdrawFrame[39;49m
[38;5;244mdrawFrame[39;49m
[38;5;244m[_handlePersistentFrameCallback][39;49m
[38;5;244m[_invokeFrameCallback][39;49m
[38;5;244mhandleDrawFrame[39;49m
[38;5;244m<fn>[39;49m
[38;5;248minternalCallback (package:dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart:50:19)[39;49m
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#45f11:
creator: CustomPaint ← ConstrainedBox ← Container ← _BodyBuilder ← MediaQuery ←
LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ←
AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#282e4 ink renderer] ←
NotificationListener<LayoutChangedNotification> ← ⋯
parentData: <none> (can use size)
constraints: BoxConstraints(w=1280.0, h=642.0)
size: Size(1280.0, 642.0)
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════
`

**Comment by quentinleguennec** [comment]
Well, a bit late to answer, but it looks like the issue solved itself in the mean time, so I'll close that.
