### ISSUE TITLE
Library throws an Exception when path is too short.

### ISSUE THREAD

**Issue by Freancy** [quentinleguennec/flutter-arrow-path#2]
`path.moveTo(start.x, start.y);`
 `path.lineTo(end.x, end.y);`
` ArrowPath.make(path: path);`
When `start` and `end` are too similar an Exception is thrown. It needs to check `path.computeMetrics().length` in function `Path _make()`

**Comment by quentinleguennec** [comment]
Thanks @Freancy, I just updated the plugin to solve the issue (better later than never).
