### ISSUE TITLE
How make dash dash style the line??

### ISSUE THREAD

**Issue by rahmanrezaee** [quentinleguennec/flutter-arrow-path#4]
![image](https://user-images.githubusercontent.com/37028113/135662204-8f39f71e-b790-4f3a-9073-1b6a3400ac2b.png)

**Comment by quentinleguennec** [comment]
Hi @rahmanrezaee, that would fall outside the scope of this plugin, which really is meant to only add the arrow head. 
But you could create your own path with the dashes (not easy to do but there might be plugins for this around) and then add the arrow head to it using this plugin.
